### ISSUE TITLE
Having Error Please Help

### ISSUE THREAD

**Issue by gurutto-manila** [ihslimn/jet-form-builder-check-query-action#1]
![image](https://github.com/ihslimn/jet-form-builder-check-query-action/assets/125864240/0ffa4431-d2c5-4d9e-ad7f-5b31b696c001)
ReferenceError: JetEngineListingData is not defined
    at https://mydomain/wp-content/plugins/jet-form-builder-check-query-action-main/assets/js/builder.editor.js?ver=1.1.0:1:347
    at wt (https://c0.wp.com/c/6.5.2/wp-includes/js/dist/vendor/react-dom.min.js:10:47637)
    at js (https://c0.wp.com/c/6.5.2/wp-includes/js/dist/vendor/react-dom.min.js:10:120584)
    at wl (https://c0.wp.com/c/6.5.2/wp-includes/js/dist/vendor/react-dom.min.js:10:88659)
    at bl (https://c0.wp.com/c/6.5.2/wp-includes/js/dist/vendor/react-dom.min.js:10:88587)
    at yl (https://c0.wp.com/c/6.5.2/wp-includes/js/dist/vendor/react-dom.min.js:10:88450)
    at il (https://c0.wp.com/c/6.5.2/wp-includes/js/dist/vendor/react-dom.min.js:10:85274)
    at fl (https://c0.wp.com/c/6.5.2/wp-includes/js/dist/vendor/react-dom.min.js:10:85661)
    at Nn (https://c0.wp.com/c/6.5.2/wp-includes/js/dist/vendor/react-dom.min.js:10:32474)
    at https://c0.wp.com/c/6.5.2/wp-includes/js/dist/vendor/react-dom.min.js:10:83226

**Comment by ihslimn** [comment]
It may happen if you have no JetEngine installed, I don't see the other reason it may happen as of now

yet it should not happen at all :)
so I cannot say for sure without having this reproduced

**Comment by gurutto-manila** [comment]
![image](https://github.com/ihslimn/jet-form-builder-check-query-action/assets/125864240/2451fdc3-d17a-426c-814d-f37e06f89fb7)
jetengine is installed, not compatible with wordpress 6.5.2?

**Comment by gurutto-manila** [comment]
@ihslimn 
here is the error

(()=>{var e={501:()=>{var e=wp.components,t=e.TextControl,n=e.ToggleControl,r=e.SelectControl;(0,JetFBActions.addAction)("jfbc_check_query",(function(e){var o=e.settings,l=e.label,a=e.onChangeSetting;return wp.element.createElement(React.Fragment,null,wp.element.createElement(r,{label:l("query_id"),labelPosition:"side",value:o.query_id,options:JetEngineListingData.queriesList,onChange:function(e){return a(e,"query_id")},__nextHasNoMarginBottom:!0}),wp.element.createElement(t,{label:l("error_message"),value:o.error_message,onChange:function(e){return a(e,"error_message")}}),wp.element.createElement(n,{label:l("on_has_results"),help:o.on_has_results?"Form will throw an error if query has results.":"Form will throw an error if query has no results.",checked:o.on_has_results,onChange:function(e){return a(e,"on_has_results")}}))}))},931:()=>{var e=wp.components,t=e.TextControl,n=e.SelectControl,r=e.ToggleControl;(0,JetFBActions.addAction)("jfbc_get_query_values",(function(e){var o,l=e.settings,a=e.label,u=e.onChangeSetting;return wp.element.createElement(React.Fragment,null,wp.element.createElement(n,{label:a("query_id"),labelPosition:"side",value:l.query_id,options:JetEngineListingData.queriesList,onChange:function(e){return u(e,"query_id")},__nextHasNoMarginBottom:!0}),wp.element.createElement(t,{label:a("store_to"),value:l.store_to,onChange:function(e){return u(e,"store_to")}}),wp.element.createElement(t,{label:a("count_to"),help:a("count_to_description"),value:l.count_to,onChange:function(e){return u(e,"count_to")}}),wp.element.createElement(r,{label:a("get_one"),checked:null!==(o=l.get_one)&&void 0!==o&&o,onChange:function(e){return u(e,"get_one")}}),l.get_one&&wp.element.createElement(t,{label:a("property"),value:l.property,onChange:function(e){return u(e,"property")}}))}))}},t={};function n(r){var o=t[r];if(void 0!==o)return o.exports;var l=t[r]={exports:{}};return e[r](l,l.exports,n),l.exports}n.n=e=>{var t=e&&e.__esModule?()=>e.default:()=>e;return n.d(t,{a:t}),t},n.d=(e,t)=>{for(var r in t)n.o(t,r)&&!n.o(e,r)&&Object.defineProperty(e,r,{enumerable:!0,get:t[r]})},n.o=(e,t)=>Object.prototype.hasOwnProperty.call(e,t),(()=>{"use strict";n(501),n(931)})()})();

**Comment by ihslimn** [comment]
this is not an error but the script :)
again - as I have no such error, I cannot tell you what goes wrong

as to ny knowledge, there are no issues with JetEngine compatibility

try disabling all plugins except for JetFormBuilder, JetEngine, and this addon; if the problem goes away then you have some third-party plugin compatibility issue

**Comment by gurutto-manila** [comment]
i found out the problem
make sure to turn on this function in jetengine

![image](https://github.com/ihslimn/jet-form-builder-check-query-action/assets/125864240/759d54fd-520f-4157-882f-ebaa717d5edd)

thanks for the response sir, more power
